-
  name: 'Execute two commands on localhost'
  hosts: localhost
  tasks:
    -
      name: 'Execute a date command'
      command: date
    -
      name: 'Executeacommandtodisplayhostsfile'
      command: cat /E:/Ansible